# Site settings
title: Charisa Codes
header-img: img/home-bg.png
email: charisaanne@gmail.com
copyright_name: CLackrone
description: > # this means to ignore newlines until "baseurl:"
  Learning to code in a world of preschoolers
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CLackrone
learn_profile: CLackrone
email_username: charisaanne@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
